# Railway Deployment Check Configuration
# This file configures Railway to wait for GitHub Actions checks before deploying

# Required status checks that must pass before Railway deploys
required_checks:
  - "Test Status Check"  # The final status check from our test workflow
  - "test (3.11)"       # Python 3.11 tests
  - "test (3.12)"       # Python 3.12 tests
  - "test (3.13)"       # Python 3.13 tests

# Deployment settings
deployment:
  # Only deploy from main branch
  branch: main
  # Wait for all checks to pass
  wait_for_checks: true
  # Maximum wait time (in seconds)
  check_timeout: 1800  # 30 minutes
  
# Auto-deploy settings
auto_deploy:
  enabled: true
  # Only auto-deploy when all checks pass
  require_checks: true