# Nixpacks configuration for Railway deployment with integrated testing
# This configuration runs tests during the build phase

[phases.setup]
nixPkgs = ["python310", "gcc", "postgresql", "redis"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "echo '📦 Dependencies installed successfully'"
]

[phases.test]
dependsOn = ["install"]
cmds = [
    # Create test environment
    "echo '🧪 Running unit tests before deployment...'",
    "echo '================================'",
    
    # Set up test database
    "export DATABASE_URL=sqlite:///test.db",
    "export FLASK_ENV=testing",
    "export SECRET_KEY=railway-test-secret-key",
    "export REDIS_URL=redis://localhost:6379/0",
    "export OAUTHLIB_INSECURE_TRANSPORT=1",
    "export CI=true",
    "export MODAL_ML_BASE_URL=https://theresaanna--sentiment-ml-service-fastapi-app.modal.run",
    
    # Run tests with detailed output
    '''
    python -m pytest tests/ \
        -v \
        --tb=short \
        --maxfail=10 \
        --disable-warnings \
        -k "not integration" \
        || (echo "❌ Unit tests failed! Deployment aborted." && exit 1)
    ''',
    
    "echo '✅ All unit tests passed!'",
    "echo '================================'"
]

[phases.build]
dependsOn = ["test"]
cmds = [
    # No model downloads needed - using Modal ML service
    "echo '🚀 Using Modal ML service for sentiment analysis'",
    "echo '✅ Build complete!'"
]

[start]
cmd = "python scripts/railway_startup.py && gunicorn --bind 0.0.0.0:${PORT:-8000} --timeout 120 --workers 1 --threads 4 --worker-class gthread run:app"

[variables]
RAILWAY_RUN_TESTS = "true"
PYTEST_OPTIONS = "-v --tb=short"