# Nixpacks configuration for Railway deployment with integrated testing
# This configuration runs tests during the build phase

[phases.setup]
# Include Python and build tools, plus pip/virtualenv from Nix to guarantee availability
nixPkgs = [
  "python311",
  "gcc",
  "postgresql",
  "redis",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "python311Packages.virtualenv"
]

[phases.install]
# Create and use a dedicated venv; rely on Nix-provided pip/virtualenv
cmds = [
    "python3 -V",
    "python3 -m pip --version || true",
    "python3 -m pip install --upgrade pip setuptools wheel virtualenv",
    "python3 -m virtualenv /opt/venv",
    "/opt/venv/bin/pip --version",
    "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
    "/opt/venv/bin/pip install -r requirements.txt",
    "echo '📦 Dependencies installed successfully'"
]

[phases.test]
dependsOn = ["install"]
cmds = [
    # Run tests with the venv Python so dependencies resolve correctly
    "/opt/venv/bin/python scripts/run_tests_railway.py"
]

[phases.build]
dependsOn = ["test"]
cmds = [
    # No model downloads needed - using Modal ML service
    "echo '🚀 Using Modal ML service for sentiment analysis'",
    "echo '✅ Build complete!'"
]

# Start command is defined in Procfile

[start]
# Explicitly use venv Python for runtime
cmd = "/opt/venv/bin/python railway_start.py"

[variables]
RAILWAY_RUN_TESTS = "true"
PYTEST_OPTIONS = "-v --tb=short"
