# Nixpacks configuration for Railway deployment with integrated testing
# This configuration runs tests during the build phase

[phases.setup]
nixPkgs = ["python310", "gcc", "postgresql", "redis"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "echo '📦 Dependencies installed successfully'"
]

[phases.test]
dependsOn = ["install"]
cmds = [
    # Use the Railway test runner script which respects RAILWAY_RUN_TESTS variable
    "python scripts/run_tests_railway.py"
]

[phases.build]
dependsOn = ["test"]
cmds = [
    # No model downloads needed - using Modal ML service
    "echo '🚀 Using Modal ML service for sentiment analysis'",
    "echo '✅ Build complete!'"
]

[start]
cmd = "python scripts/railway_startup.py && python start.py"

[variables]
RAILWAY_RUN_TESTS = "true"
PYTEST_OPTIONS = "-v --tb=short"