[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql_16", "gcc"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["./railway_build.sh"]

[start]
cmd = "gunicorn run:app"
