services:
  # Main web service for the sentiment analyzer
  - type: web
    name: sentiment-analyzer
    runtime: python
    runtime_version: python-3.11.10
    region: oregon # You can change to: ohio, frankfurt, singapore
    plan: free # Options: free, starter ($7/mo), standard ($25/mo)
    
    # Build configuration
    buildCommand: "./build.sh"
    
    # Start command using gunicorn for production
    startCommand: gunicorn run:app --workers 2 --threads 4 --worker-class sync --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5 --log-level info
    
    # Health check endpoint
    healthCheckPath: /
    
    # Environment variables
    envVars:
      # Flask configuration
      - key: FLASK_ENV
        value: production
      
      - key: FLASK_DEBUG
        value: false
      
      # Secret key - generate a new one in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      
      # YouTube API key - set this in Render dashboard
      - key: YOUTUBE_API_KEY
        sync: false # Must be set manually in Render dashboard
      
      # Redis Cloud connection - set this in Render dashboard
      - key: REDIS_URL
        sync: false # Must be set manually in Render dashboard
      
      # Application settings
      - key: MAX_COMMENTS_PER_VIDEO
        value: 10000
      
      - key: CACHE_TIMEOUT
        value: 300
      
      # Python optimizations for ML models
      - key: PYTHONUNBUFFERED
        value: 1
      
      - key: TOKENIZERS_PARALLELISM
        value: false
      
      # Model caching directory
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache/huggingface
      
      # OpenAI API key if using GPT models - set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false # Optional - set if using OpenAI
    
    # Scaling configuration
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80
    
    # Disk configuration for model caching (optional, for paid plans)
    # disk:
    #   name: sentiment-models
    #   mountPath: /opt/render/project/.cache
    #   sizeGB: 10

# Optional: PostgreSQL database if you need persistence beyond Redis
# databases:
#   - name: sentiment-db
#     plan: free # Options: free, starter ($7/mo), standard ($15/mo)
#     databaseName: sentiment_analyzer
#     user: sentiment_user

# Build and deploy configuration
buildFilter:
  paths:
    - app/**
    - requirements.txt
    - requirements-production.txt
    - requirements-render.txt
    - runtime.txt
    - run.py
    - render.yaml
  ignoredPaths:
    - tests/**
    - .pytest_cache/**
    - __pycache__/**
    - .git/**
    - .env
    - .env.local
    - venv/**
    - env/**
    - *.pyc
    - .DS_Store
