"""Add include_replies column to analysis_job table

Revision ID: 078c7c5dd96c
Revises: cfe8c2fdf688
Create Date: 2025-09-15 18:03:26.620565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078c7c5dd96c'
down_revision = 'cfe8c2fdf688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_replies', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_job', schema=None) as batch_op:
        batch_op.drop_column('include_replies')

    # ### end Alembic commands ###
