"""Add AnalysisJob table for queued sentiment analysis

Revision ID: cfe8c2fdf688
Revises: a140228fb140
Create Date: 2025-09-14 23:04:11.505658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe8c2fdf688'
down_revision = 'a140228fb140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('video_title', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('channel_name', sa.String(length=200), nullable=True),
    sa.Column('comment_count_requested', sa.Integer(), nullable=False),
    sa.Column('comment_count_processed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_job_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_job_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_job_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_job_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_job_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_job_job_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_job_created_at'))

    op.drop_table('analysis_job')
    # ### end Alembic commands ###
